---
apiVersion: v1
kind: Secret
metadata:
  name: mstendel-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-demo/mstendel-backend-gitops
